apiVersion: skaffold/v4beta2
kind: Config
deploy:
  kubectl: {}
manifests:
  rawYaml:
  - ./infrastructure/k8s/*
build:
  tagPolicy:
    sha256: {}
  local:
    push: true
  artifacts:
    - image: danielkimtor15/auth
      context: auth
      docker:
       dockerfile: Dockerfile
      sync:
        manual:
         -  src: 'src/**/*.ts'
            dest: .